function createfigure(YMatrix1, YMatrix2, YMatrix3, YMatrix4)
%CREATEFIGURE(YMatrix1, YMatrix2, YMatrix3, YMatrix4)
%  YMATRIX1:  matrix of y data
%  YMATRIX2:  matrix of y data
%  YMATRIX3:  matrix of y data
%  YMATRIX4:  matrix of y data

%  Auto-generated by MATLAB on 11-Apr-2022 12:51:13

% Create figure
figure1 = figure('Renderer','painters');

% Create subplot
subplot1 = subplot(2,2,1,'Parent',figure1);
hold(subplot1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'Parent',subplot1,'LineWidth',5);
set(plot1(1),'DisplayName','Phase a');
set(plot1(2),'DisplayName','Phase b');
set(plot1(3),'DisplayName','Phase c');
set(plot1(4),'DisplayName',['0.95 p.u.',newline,'limit'],'LineStyle','--',...
    'Color',[0 0 0]);

% Create ylabel
ylabel('Voltage in PU');

% Create xlabel
xlabel('Time');

% Create title
title({'Voltage variation for bus 634','at normal conditions (base kV = 0.4 kV)'});

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot1,[1 96]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot1,[0.93992 1]);
grid(subplot1,'on');
% Set the remaining axes properties
set(subplot1,'FontSize',15,'XTick',[1 48.5 96],'XTickLabel',...
    {'12:00 am','12:00 pm','12:00 am'});
% Create legend
legend1 = legend(subplot1,'show');
set(legend1,'Location','eastoutside','FontSize',13);

% Create subplot
subplot2 = subplot(2,2,2,'Parent',figure1);
hold(subplot2,'on');

% Create multiple lines using matrix input to plot
plot2 = plot(YMatrix2,'Parent',subplot2,'LineWidth',3);
set(plot2(1),'DisplayName','Phase a');
set(plot2(2),'DisplayName','Phase b');
set(plot2(3),'DisplayName','Phase c');
set(plot2(4),'DisplayName',['0.95 p.u.',newline,'limit'],'LineStyle','--',...
    'Color',[0 0 0]);

% Create ylabel
ylabel('Voltage in PU');

% Create xlabel
xlabel('Time');

% Create title
title({'Voltage variation for bus 634','at normal conditions (base kV = 0.4 kV)'});

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot2,[1 96]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot2,[0.93348 1]);
grid(subplot2,'on');
% Set the remaining axes properties
set(subplot2,'FontSize',15,'XTick',[1 48.5 96],'XTickLabel',...
    {'12:00 am','12:00 pm','12:00 am'});
% Create legend
legend2 = legend(subplot2,'show');
set(legend2,'Location','eastoutside','FontSize',13);

% Create subplot
subplot3 = subplot(2,2,3,'Parent',figure1);
hold(subplot3,'on');

% Create multiple lines using matrix input to plot
plot3 = plot(YMatrix3,'Parent',subplot3,'LineWidth',3);
set(plot3(1),'DisplayName','Phase a');
set(plot3(2),'DisplayName','Phase b');
set(plot3(3),'DisplayName','Phase c');
set(plot3(4),'DisplayName',['0.95 p.u.',newline,'limit'],'LineStyle','--',...
    'Color',[0 0 0]);

% Create ylabel
ylabel('Voltage in PU');

% Create xlabel
xlabel('Time');

% Create title
title({'Voltage variation for bus 634','at normal conditions (base kV = 0.4 kV)'});

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot3,[1 96]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot3,[0.92368 1]);
grid(subplot3,'on');
% Set the remaining axes properties
set(subplot3,'FontSize',15,'XTick',[1 48.5 96],'XTickLabel',...
    {'12:00 am','12:00 pm','12:00 am'});
% Create legend
legend3 = legend(subplot3,'show');
set(legend3,'Location','eastoutside','FontSize',13);

% Create subplot
subplot4 = subplot(2,2,4,'Parent',figure1);
hold(subplot4,'on');

% Create multiple lines using matrix input to plot
plot4 = plot(YMatrix4,'Parent',subplot4,'LineWidth',3);
set(plot4(1),'DisplayName','Phase a');
set(plot4(2),'DisplayName','Phase b');
set(plot4(3),'DisplayName','Phase c');
set(plot4(4),'DisplayName',['0.95 p.u.',newline,'limit'],'LineStyle','--',...
    'Color',[0 0 0]);

% Create ylabel
ylabel('Voltage in PU');

% Create xlabel
xlabel('Time');

% Create title
title({'Voltage variation for bus 634','at normal conditions (base kV = 0.4 kV)'});

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot4,[1 96]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot4,[0.90089 1]);
grid(subplot4,'on');
% Set the remaining axes properties
set(subplot4,'FontSize',15,'XTick',[1 48.5 96],'XTickLabel',...
    {'12:00 am','12:00 pm','12:00 am'});
% Create legend
legend4 = legend(subplot4,'show');
set(legend4,'Location','eastoutside','FontSize',13);

